import { sqliteAdapter } from '@payloadcms/db-sqlite'
import { lexicalEditor } from '@payloadcms/richtext-lexical'
import { vercelBlobStorage } from '@payloadcms/storage-vercel-blob'
import { de } from '@payloadcms/translations/languages/de'
import path from 'path'
import { buildConfig } from 'payload'
import { fileURLToPath } from 'url'
import sharp from 'sharp'

import { Media } from './collections/Media'
import { Projects } from './collections/Projects'
import { Users } from './collections/Users'
import { Homepage } from './globals/Homepage'
import { Settings } from './globals/Settings'
import { StudioPage } from './globals/StudioPage'

const filename = fileURLToPath(import.meta.url)
const dirname = path.dirname(filename)

export default buildConfig({
  admin: {
    user: Users.slug,
    // Brand palette is light; a dark variant is intentionally not offered
    theme: 'light',
    components: {
      graphics: {
        Logo: '/components/admin/Logo#Logo',
        Icon: '/components/admin/Icon#Icon',
      },
    },
    importMap: {
      baseDir: path.resolve(dirname),
    },
    meta: {
      titleSuffix: ' - Studio Lichtblick',
    },
  },
  collections: [Projects, Media, Users],
  globals: [Settings, Homepage, StudioPage],
  editor: lexicalEditor(),
  // The frontend reads exclusively via the Payload local API; GraphQL is unused
  // attack surface (incl. auth mutations), so it is turned off entirely.
  graphQL: {
    disable: true,
  },
  i18n: {
    supportedLanguages: { de },
    fallbackLanguage: 'de',
  },
  secret: process.env.PAYLOAD_SECRET || '',
  typescript: {
    outputFile: path.resolve(dirname, 'payload-types.ts'),
  },
  db: sqliteAdapter({
    client: {
      // Local dev: a SQLite file. Production: a remote Turso (libSQL) URL
      // (libsql://…turso.io) plus an auth token — same adapter, one engine.
      url: process.env.DATABASE_URL || 'file:./lichtblick.db',
      authToken: process.env.DATABASE_AUTH_TOKEN,
    },
  }),
  sharp,
  // Media lives on the local disk in dev; on Vercel Blob in production. The
  // plugin only loads when its token is present, so local dev and the reseed
  // workflow keep using the filesystem (the adapter also rejects a malformed
  // token at startup, so it must be absent — not empty — without Blob).
  // NOTE: importMap.js is committed WITH the plugin's client upload handler,
  // generated by running `generate:importmap` with a real-format
  // BLOB_READ_WRITE_TOKEN set; the committed map is what production uses.
  plugins: process.env.BLOB_READ_WRITE_TOKEN
    ? [
        vercelBlobStorage({
          enabled: true,
          collections: { media: true },
          token: process.env.BLOB_READ_WRITE_TOKEN,
        }),
      ]
    : [],
})
